name: sergioja-local-proxy

services:
  docker-socket-proxy-local:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy-local
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
      TASKS: 1
      INFO: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - sergioja-network-dev

  traefik-local:
    image: traefik:2.11
    container_name: sergioja-traefik-local
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=sergioja-network-dev"
      - "--providers.docker.endpoint=tcp://docker-socket-proxy-local:2375"
      - "--entrypoints.web.address=:8080"
    ports:
      - "8080:8080"
    depends_on:
      - docker-socket-proxy-local
    networks:
      - sergioja-network-dev

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - sergioja-network-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.who.rule=Host(`who.localhost`)"
      - "traefik.http.routers.who.entrypoints=web"
      - "traefik.http.services.who.loadbalancer.server.port=80"

networks:
  sergioja-network-dev:
    external: true
